twitter:
  auth:
    api-key: ${TWITTER_CONSUMER_KEY}
    api-key-secret: ${TWITTER_CONSUMER_SECRET}
    access-token: ${TWITTER_ACCESS_TOKEN}
    access-token-secret: ${TWITTER_ACCESS_TOKEN_SECRET}
bot:
  tweetfreq:
    thirty-minutes: 1800000
    five-minutes: 300000
    hour: 3600000
    four-hours: 14400000
    day: 86400000
